# Site settings
title: SOUFIANE FARTIT
description: A personal portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Soufiane Fartit
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Data Scientist
email: soufiane.fartit@gmail.com
twitter_username: fartit
github_username:  soufiane-fartit
gplus_username:  soufiane-fartit
linkedin_username:  soufiane-fartit

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
